name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # adjust to your actual version

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd backend/AutoShip
          dotnet-sonarscanner begin /k:"sadatakhtar_AutoShip" /o:"sadatakhtar" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
          dotnet build AutoShip.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"



